PADDING_TOKEN = '[pad]'
SEPERATION_TOKEN = '[sep]'
CLASSIFIER_TOKEN = '[cls]'
UNKNOWN_TOKEN = '[unk]'
DEFAULT_TOKEN_ORDER = [
    PADDING_TOKEN, SEPERATION_TOKEN, CLASSIFIER_TOKEN, UNKNOWN_TOKEN
]

WHSP_AND_PUNCTS = "[\w']+|[.!?]"
STOPS = '.!?'
